// @module spec-verifier
// @exports verifyObservationsAgainstContract, SpecClarifiedJson, SpecFeature, VerificationResult, VerificationFailure
// @entry roadmap

import type { ObservationResult } from '../protocol.ts';

// ── Types ─────────────────────────────────────────────────────────────────────

/** A single feature expectation in the clarified spec contract. */
export interface SpecFeature {
  id: string;
  selector?: string;
  observation: 'visible' | 'interactive' | 'contrast' | 'toggles-class' | 'count' | 'text' | 'style' | 'size' | 'attribute' | 'class' | 'overflow';
  evidence: string;
  minRatio?: number;    // for contrast observations
  minCount?: number;    // for count observations
  expected?: string;    // for text/attribute/class observations
}

/** Machine-readable contract generated by init gate, consumed by terminal gate. */
export interface SpecClarifiedJson {
  features: SpecFeature[];
  gaps: string[];
  confidence: number;
  generated: string; // ISO-8601
}

/** A single verification failure. */
export interface VerificationFailure {
  id: string;
  expected: string;
  actual: string;
  evidence: string;
}

/** Result of verifying observations against a spec contract. */
export interface VerificationResult {
  passed: boolean;
  matched: number;
  failed: number;
  unmatched: string[];  // feature IDs with no corresponding observation
  failures: VerificationFailure[];
}

// ── Core ──────────────────────────────────────────────────────────────────────

/**
 * Verify explore observations against a spec-clarified contract.
 *
 * For each feature in the contract:
 * 1. Find the observation with matching ID
 * 2. Check pass/fail from the observation
 * 3. For typed checks (contrast ratio, count), compare evidence values
 *
 * Features without a matching observation are recorded as unmatched.
 */
export function verifyObservationsAgainstContract(
  spec: SpecClarifiedJson,
  observations: ObservationResult[],
): VerificationResult {
  const obsMap = new Map(observations.map(o => [o.id, o]));
  const failures: VerificationFailure[] = [];
  const unmatched: string[] = [];
  let matched = 0;

  for (const feature of spec.features) {
    const obs = obsMap.get(feature.id);

    if (!obs) {
      unmatched.push(feature.id);
      continue;
    }

    matched++;

    if (!obs.pass) {
      failures.push({
        id: feature.id,
        expected: describeExpectation(feature),
        actual: obs.evidence,
        evidence: obs.evidence,
      });
      continue;
    }

    // Typed value checks beyond pass/fail
    const valueFailure = checkTypedValue(feature, obs);
    if (valueFailure) {
      failures.push(valueFailure);
    }
  }

  return {
    passed: failures.length === 0 && unmatched.length === 0,
    matched,
    failed: failures.length,
    unmatched,
    failures,
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function describeExpectation(feature: SpecFeature): string {
  switch (feature.observation) {
    case 'visible':
      return `${feature.selector} visible`;
    case 'interactive':
      return `${feature.selector} interactive`;
    case 'contrast':
      return `contrast ratio >= ${feature.minRatio ?? 4.5}:1`;
    case 'count':
      return `count >= ${feature.minCount ?? 1}`;
    case 'text':
      return `text matches "${feature.expected}"`;
    default:
      return `${feature.observation}: ${feature.selector ?? feature.id}`;
  }
}

/** Compare typed observation values against spec thresholds. */
function checkTypedValue(feature: SpecFeature, obs: ObservationResult): VerificationFailure | null {
  if (feature.observation === 'contrast' && feature.minRatio != null && typeof obs.value === 'number') {
    if (obs.value < feature.minRatio) {
      return {
        id: feature.id,
        expected: `contrast ratio >= ${feature.minRatio}:1`,
        actual: `contrast ratio ${obs.value.toFixed(2)}:1`,
        evidence: obs.evidence,
      };
    }
  }

  if (feature.observation === 'count' && feature.minCount != null && typeof obs.value === 'number') {
    if (obs.value < feature.minCount) {
      return {
        id: feature.id,
        expected: `count >= ${feature.minCount}`,
        actual: `count = ${obs.value}`,
        evidence: obs.evidence,
      };
    }
  }

  return null;
}
