/**
 * Auto-generate roadmap.ts from ProjectMetadata + BuildProcess
 *
 * Generates a minimal 3-node DAG:
 * init (project setup) → build → term (ready for deployment)
 *
 * The generated roadmap:
 * - Passes verify(), check() without user edits
 * - All nodes marked idempotent: true (agents can safely re-run)
 * - Can be extended with reconcile() to add custom phases
 */

import type { ProjectMetadata } from './project-metadata.schema';
import type { NodeSpec, Graph } from './protocol';
import { check, verify, define } from './protocol';

export interface GeneratedDAG {
  sourceCode: string; // The roadmap.ts code
  dag: Graph<'init' | 'build' | 'term'>; // The parsed DAG
}

/**
 * Generate roadmap DAG from project metadata
 */
export function generateRoadmapDAG(
  projectId: string,
  metadata: ProjectMetadata,
  buildCommand: string,
): GeneratedDAG {
  const buildOutput = inferBuildOutput(metadata, buildCommand);

  // init produces: metadata.init + node_modules (always needed)
  const initProduces = Array.from(new Set([
    'node_modules',
    ...metadata.init,
  ]));

  // build consumes: only what init produces (metadata.init files + node_modules)
  // Don't infer additional config files — they should be in metadata.init if needed
  const buildConsumes = Array.from(new Set([
    ...initProduces.filter(p => p !== 'node_modules'), // consume source files from init
  ]));

  const dag: Graph<'init' | 'build' | 'term'> = {
    id: projectId,
    desc: `Project roadmap for ${projectId} (auto-generated by roadmap integrate)`,
    init: 'init',
    term: 'term',
    nodes: {
      init: {
        id: 'init',
        desc: 'Initialize project: install dependencies, setup environment',
        produces: initProduces,
        consumes: [],
        deps: [],
        validate: [
          { type: 'artifact-exists', target: 'node_modules' },
        ],
        idempotent: true,
      },
      build: {
        id: 'build',
        desc: `Build project: ${buildCommand}`,
        produces: buildOutput,
        consumes: buildConsumes,
        deps: ['init'],
        validate: [
          ...buildOutput.map(artifact => ({ type: 'artifact-exists' as const, target: artifact })),
        ],
        idempotent: true,
      },
      term: {
        id: 'term',
        desc: 'Project ready (build complete, artifacts available)',
        produces: [],
        consumes: buildOutput,
        deps: ['build'],
        validate: [],
        idempotent: false,
      },
    },
  };

  // Validate the generated DAG
  try {
    define(dag); // Check structure
  } catch (e) {
    throw new Error(`Generated DAG failed define(): ${e instanceof Error ? e.message : String(e)}`);
  }

  const checkResult = check(dag);
  if (!checkResult.done) {
    throw new Error(`Generated DAG not fully connected: orphans=${checkResult.orphans}`);
  }

  const verifyErrors = verify(dag);
  if (verifyErrors.length) {
    throw new Error(`Generated DAG contract violations: ${verifyErrors.join(', ')}`);
  }

  const sourceCode = generateSourceCode(projectId, metadata, buildCommand, buildOutput, buildConsumes);

  return { sourceCode, dag };
}

/**
 * Infer build output directory/files
 */
function inferBuildOutput(metadata: ProjectMetadata, buildCommand: string): string[] {
  // Common patterns from buildCommand
  if (buildCommand.includes('tsc')) return ['dist', 'lib', '*.d.ts'];
  if (buildCommand.includes('esbuild')) return ['dist'];
  if (buildCommand.includes('vite')) return ['dist'];
  if (buildCommand.includes('rollup')) return ['dist'];
  if (buildCommand.includes('webpack')) return ['dist'];
  if (buildCommand.includes('parcel')) return ['dist'];

  // Default based on projectType
  if (metadata.projectType?.includes('typescript')) return ['dist', 'lib', '*.d.ts'];
  if (metadata.projectType?.includes('webapp')) return ['dist'];
  if (metadata.projectType?.includes('library')) return ['lib', '*.d.ts'];

  // Fallback
  return ['dist'];
}

/**
 * Infer source file patterns from project type
 */
function inferSourceFiles(metadata: ProjectMetadata): string[] {
  const files: string[] = [];

  if (metadata.projectType?.includes('typescript')) {
    files.push('src/**/*.ts');
  } else if (metadata.projectType?.includes('javascript')) {
    files.push('src/**/*.js');
  }

  if (metadata.projectType?.includes('webapp') || metadata.projectType?.includes('react')) {
    files.push('src/**/*.tsx', 'src/**/*.jsx');
  }

  if (!files.length) {
    files.push('src');
  }

  return files;
}

/**
 * Infer config files based on project type
 */
function inferConfigFiles(metadata: ProjectMetadata): string[] {
  const configs: string[] = [];

  if (metadata.projectType?.includes('typescript')) {
    configs.push('tsconfig.json');
  }

  if (metadata.buildCommand?.includes('tsc')) {
    configs.push('tsconfig.json');
  }

  // Always include package.json in consumes (handled separately in generateSourceCode)
  return Array.from(new Set(configs));
}

/**
 * Generate roadmap.ts source code
 */
function generateSourceCode(
  projectId: string,
  metadata: ProjectMetadata,
  buildCommand: string,
  buildOutput: string[],
  buildConsumes: string[],
): string {
  const buildOutputStr = buildOutput.map(o => `    '${o}',`).join('\n');
  const consumesStr = buildConsumes
    .map(s => `    '${s}',`)
    .join('\n');

  return `#!/usr/bin/env node
/**
 * Project roadmap
 *
 * Auto-generated by: roadmap integrate
 * Date: ${new Date().toISOString()}
 *
 * This DAG defines the project lifecycle:
 * init → build → term
 *
 * To extend: use reconcile(dag, fwd, bwd) to add custom phases
 */

import { define, graph } from 'roadmap/protocol';

export default define(graph({
  id: '${projectId}',
  desc: 'Project roadmap for ${projectId}',
  init: 'init',
  term: 'term',
  nodes: {
    init: {
      id: 'init',
      desc: 'Initialize project: install dependencies, setup environment',
      produces: [
        'node_modules',
        '.git/hooks',
      ],
      consumes: [],
      deps: [],
      idempotent: true,
    },
    build: {
      id: 'build',
      desc: 'Build project: ${buildCommand}',
      produces: [
${buildOutputStr}
      ],
      consumes: [
${consumesStr}
      ],
      deps: ['init'],
      idempotent: true,
    },
    term: {
      id: 'term',
      desc: 'Project ready (build complete, artifacts available)',
      produces: [],
      consumes: [
${buildOutputStr}
      ],
      deps: ['build'],
      idempotent: false,
    },
  },
}));

/**
 * To use this roadmap in your project:
 *
 * 1. Check your position:
 *    import { orient } from 'roadmap/protocol';
 *    import roadmap from './roadmap.ts';
 *    const pos = orient(roadmap, (a) => existsSync(a));
 *    console.log(pos.position, pos.produces);
 *
 * 2. Execute phases:
 *    while (pos.position !== roadmap.term) {
 *      // Create pos.produces
 *      // Commit
 *      // Re-orient
 *    }
 *
 * 3. Add custom phases:
 *    Use reconcile() to identify gaps, then expand the DAG
 *    before this one to add test, lint, deploy phases
 */
`;
}

/**
 * Validate that generated DAG satisfies all constraints
 */
export function validateGeneratedDAG(dag: Graph<any>): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  try {
    define(dag);
  } catch (e) {
    errors.push(`define() failed: ${e instanceof Error ? e.message : String(e)}`);
  }

  const checkResult = check(dag);
  if (!checkResult.done) {
    errors.push(`DAG not fully connected: orphans=${checkResult.orphans.join(',')}`);
  }

  const verifyErrors = verify(dag);
  if (verifyErrors.length) {
    errors.push(...verifyErrors);
  }

  // All generated nodes must be idempotent (can safely re-run)
  for (const [nodeId, node] of Object.entries(dag.nodes)) {
    if (nodeId !== dag.term && !node.idempotent) {
      errors.push(`Non-terminal node "${nodeId}" must be idempotent=true`);
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
